### ISSUE TITLE
MKV is supported, but won't upload

### ISSUE THREAD

**Issue by nigels-com** [awslabs/aws-video-transcriber#1]
The page says that: _MP4, MKV or MOV videos can be uploaded._

But an MKV upload is refused:
![screenshot from 2019-03-03 22-10-46](https://user-images.githubusercontent.com/545677/53695200-1420dc80-3e04-11e9-88e1-aa4be99f9f7d.png)

(But it works if I rename it to .mp4)

**Comment by jospas** [comment]
Hi Nigel,

Confirmed this is an issue with the user interface validating for MOV and MP4 but not allowing MKV I'm putting in a fix,

Josh
