### ISSUE TITLE
Is there a limit on file size upload through the web ui?

### ISSUE THREAD

**Issue by dariushazimi** [awslabs/aws-video-transcriber#11]
Is there a limit on file size upload through the web ui?
i.e. Can I upload a video file ~ 700MB?

Thanks

**Comment by jospas** [comment]
Yes it is currently just under the maximum file size limit for S3 ie: 5 Gig otherwise I would need to implement multipart uploads.

Videos are restricted to 2 hours in length as a hard limit by Amazon Transcribe.

The upload max size is defined by maxFilesize in:

https://github.com/awslabs/aws-video-transcriber/blob/master/web/templates/videos.hbs

```
	maxFiles: 5,
	*maxFilesize: 5119,
	acceptedFiles: 'video/mp4,video/quicktime,.mkv',

```

**Comment by dariushazimi** [comment]
@jospas 
I am trying to figure out how to setup login with password so that users can login, upload their video files and not share the SAME api key with everyone.
Currently, the API keys allow anyone with the API key to access the site.

Thanks

**Comment by jospas** [comment]
Hi there I think the best way would be to do this would be to integrate Amazon Cognito and provision users. That way service calls present a JWT token from Cognito and these are verified by an API Gateway Authorizer:

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html

This would replace the code that currently sends the X-API-KEY header with an Authorization token:

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

I would consider having some simple roles defined in the claims returned by Cognito so you could support admin, editors and viewers.

Here is a video detailing the process:

https://www.youtube.com/watch?v=5dbgJdcMfiU

**Comment by dariushazimi** [comment]
Thanks @jospas I will try it out. Thanks for the pointers.
