### ISSUE TITLE
Generated captions exceeds item size in DynamoDB

### ISSUE THREAD

**Issue by aashley** [awslabs/aws-video-transcriber#12]
This is Adam from Swift Media, we met at AWS Summit Sydney, we've been trying this out and it has some great potential for us. Still getting up to speed on how all the bits work but we've started running into some issues.

For videos under about 30 minutes we're not having any trouble but most things longer than that end up with a caption set that exceeds the DynamoDB 400KB item limit (In fact one 1hr 35min asset is a 2.1MB output from Transcribe).

**Comment by jospas** [comment]
Hi Adam,

Thanks for the bug report, one way to significantly reduce item size would be to remove the word confidences from each caption entry or gzip and base64 encode the content on the way in and out of Dynamo.

I'll have a look at feature flagging the storage of word confidences and see what I can do to compress the data in Dynamo.

**Comment by jospas** [comment]
I have implemented GZIP+base64 encoding of captions for storage in DynamoDB with 70-80% size reductions which should mean you won't see this issue any more. 

If we do get any repeats, I can flush the data to S3 and reference it from DynamoDB.

Josh

**Comment by jospas** [comment]
If you want to patch without redeploying, replace the function content for the following Lambda functions:

createcaptions
putcaption
getcaption

Josh
