### ISSUE TITLE
Get 500 forbidden error when trying to update vocabulary

### ISSUE THREAD

**Issue by anthkris** [awslabs/aws-video-transcriber#14]
I am trying to update the vocabulary on my deployed version but I keep getting an error that says Failed to Save Vocabulary and the console reads like this:

```
[INFO] saving vocabulary: https://ilwiplg5s7.execute-api.us-east-1.amazonaws.com/prod/vocabulary
app.js:311:2
[ERROR] error while saving vocabulary 
Error
​
columnNumber: 4479
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
fileName: "https://s3.us-east-1.amazonaws.com/prod-aws-captions-public-us-east-1-312726812299/js/axios-0.18.0.min.js"
​
lineNumber: 8
​
message: "Request failed with status code 500"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 500, statusText: "Internal Server Error", … }
​
stack: "e.exports@https://s3.us-east-1.amazonaws.com/prod-aws-captions-public-us-east-1-312726812299/js/axios-0.18.0.min.js:8:4479\ne.exports@https://s3.us-east-1.amazonaws.com/prod-aws-captions-public-us-east-1-312726812299/js/axios-0.18.0.min.js:8:4321\ne.exports/</l[h]@https://s3.us-east-1.amazonaws.com/prod-aws-captions-public-us-east-1-312726812299/js/axios-0.18.0.min.js:8:3278\n"
​
__proto__: Object { … }
app.js:333:3
```

**Comment by jospas** [comment]
Sorry for the delay in responding I have been on leave with no internet for the past 2 weeks.  It looks like the backing Lambda function is perhaps failing, can you please post any error from the CloudWatch logs for PutVocabulary Lambda function?

Can you provide some additional details on the size of vocabulary you are saving (in terms of total characters)?

**Comment by anthkris** [comment]
Thanks so much for responding! I took a gander at CloudWatch and it looks like the error was bad formatting of the vocabulary on my part. User error! It would be great if that error message were more helpful, though.

**Comment by jospas** [comment]
I'll have a look and add some better validation client side and server side error reporting thanks for noting the issue!
