### ISSUE TITLE
Any plans to upgrade Node?

### ISSUE THREAD

**Issue by anthkris** [awslabs/aws-video-transcriber#17]
I have this deployed and I started getting messages about Node 8 end of life. So I tried just upgrading each of the Lambda functions to Node 10, but everything broke. Any plans to update this to Node 10 or 12?

**Comment by jospas** [comment]
Thank you Matt I'm reviewing

**Comment by jospas** [comment]
I have merged the change to support deployment via Serverless I will update the CloudFormation one click deployments before closing this issue.

**Comment by jospas** [comment]
Upgraded to node 12
