### ISSUE TITLE
Anyone tried singing?

### ISSUE THREAD

**Issue by nigels-com** [awslabs/aws-video-transcriber#2]
![screenshot from 2019-03-03 22-33-10](https://user-images.githubusercontent.com/545677/53695266-e4be9f80-3e04-11e9-83ff-88c8ecd4196a.png)
**Took the midnight train going anywhere...**

**Comment by jospas** [comment]
Hi Nigel,

I haven't tried singing but background music will likely affect the transcription.

Here is a blog referencing using Transcribe for singing:

https://www.powershell.amsterdam/2018/05/01/when-marvin-gaye-met-amazon-transcribe-powershell-automating-subtitle-creation-part-i/
