### ISSUE TITLE
Editing Caption In/Out Points

### ISSUE THREAD

**Issue by gaborkukucska** [awslabs/aws-video-transcriber#27]
Hey,

I might be wrong here, however, I can't seem to be able to edit the in and out points of the captions...

Any ideas why?

**Comment by jospas** [comment]
Hi there,

The current user interface doesn't allow editing of caption start and edit points just the words within the allocated time (computed by maximum words and trimmed for silence).

This would require adjustment of neighbouring caption start and end points, it would be possible to implement this but would require some significant changes on the client to layout the generated captions.

Any ideas on a design for this?

Josh

**Comment by gaborkukucska** [comment]
Hi Josh,

First of all, great job on this example solution!
Yes I thought it was designed this way. It is often thought, that it is required to manually adjust the in and out points. During my tests, it often moved the last word of a sentence into it's own line, showing it for only a second.

A 'simple' solution would be to only alow the adjustment of the out point in such way that it influences the in point next entry. 

Another additional feature which would be great is to delete an entry.

In terms of a more robust design, I quite like https://amara.org/ it is an open source solution... This can obviously be simplified as most of the work is done by the AI.

Cheers,
Gabor

**Comment by gaborkukucska** [comment]
Ah and to insert an entry... sometime the AI doesn't pick up a line if the audio is a bit compromised... which unfortunatelly can happen in the low budget short documentaries that we do :)

**Comment by jospas** [comment]
Hi Gabor,

Are you interested in contributing any of these features?

I can add them to the backlog if you don't have Javascript or UI experience.

I watched the Amara editor video, I liked the way they show the captions sliding along the timeline and enabling and disabling in time.

Do you think the ability to insert / remove a caption plus another view to edit timings would suffice?

Josh

**Comment by gaborkukucska** [comment]
Hi Josh,

I'd love to, but I'm only a filmmaker :) I can hack at HTML/PHP and pretty well versed in server admin/AWS stuff, but that's about it :) ah and I'm great at finding and following tutorials LOL :D

Yes, the Amara one is nice, however, this can be simpler since the AI does a pretty good job. Yes, I think the ability to insert/remove and re-time captions would be great. 

PS: I'm also trying to implement a solution to translate the captions to a few major languages once the English version is done...
