### ISSUE TITLE
Unable to select hi-In as language

### ISSUE THREAD

**Issue by molosigns** [awslabs/aws-video-transcriber#29]
I want to use the application for hi-In.Its hindi and aws is providing support for this.But not able to use in one click deployement

**Comment by jospas** [comment]
Hi, please try again I have added en-IN and hi-IN as available locales,

Josh

**Comment by jospas** [comment]
Updated to include new requested locales, please advise if you have any issues

**Comment by molosigns** [comment]
I wanted to know if aws is going to support more transcribe languages.

I particularly want indian regional languages.

Marathi
Telgu
Bengali

Azure supports some of them

**Comment by molosigns** [comment]
-

   Amazon Supports the following, Please add support

   Tamil (ta-IN)
   -

   Telugu (te-IN)

**Comment by jospas** [comment]
Done!

**Comment by molosigns** [comment]
Thank you so much
