### ISSUE TITLE
add cloudformation template that allows to deploy local code changes.

### ISSUE THREAD

**Issue by alberthaoh** [awslabs/aws-video-transcriber#38]
Hi, 
The latest master looks really well structured and refactored. But the cloudformation template file is sam packaged? Is it possible to include the 'raw' cloudformation template that uses local files/code to deploy the solution. 
I want to change the website code and also be able to add new features/resources. As of it now, all is packaged to s3, it's not easy to do that.
Is it possible to add the template?
Thanks a lot!

**Comment by dengmingtong** [comment]
You can download template and change them by yourself

**Comment by dengmingtong** [comment]
Already added the cloudformation template in [deployment](https://github.com/awslabs/aws-video-transcriber/tree/master/deployment), please follow [guide](https://github.com/awslabs/aws-video-transcriber#custom-code-and-build-locally) to build locally.
