### ISSUE TITLE
transcoder generate bigger file size

### ISSUE THREAD

**Issue by lawrenceamer** [awslabs/aws-video-transcriber#40]
That happened while uploading MP4 video format while extracting the audio from the video; if the video length is around 2 hours, it duplicates it to 6 hours, which raises an error for a translator, since the AWS transcriber limits the audio length to no more than 4 hours.

**Comment by lawrenceamer** [comment]
So if the video was 2 hours, it becomes 9 hours!

**Comment by dengmingtong** [comment]
We haven't encountered a similar issue before, could you please share your file with me and describe your steps. I'll try to reproduce the issue in our test environment.
