### ISSUE TITLE
Stack Name Too Long

### ISSUE THREAD

**Issue by EddieGoynesAmazon** [awslabs/aws-video-transcriber#9]
If I choose too long of a Stack Name the IAM policy gives this error when it deploys. 

The name I chose TransDem2019 instead, it's a shorter name and that worked. 

![image](https://user-images.githubusercontent.com/40248820/55438005-4a619100-5555-11e9-81a3-83567df096b1.png)

**Comment by jospas** [comment]
Thanks Eddie I'm looking to add some validation on this one
